### ISSUE TITLE
Vagrant file asks for host-only network?

### ISSUE THREAD

**Issue by peterlamar** [binocarlos/powerstrip-k8s-demo#14]
Let me know if I am doing something wrong? Kicked this off on a mac with vagrant and virtualbox. 

vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'hashicorp/precise32'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'hashicorp/precise32' is up to date...
==> default: Setting the name of the VM: petlamar_default_1430408869467_5262
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 => 8000 (adapter 1)
    default: 8001 => 8001 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.2.0
    default: VirtualBox Version: 4.3
NFS requires a host-only network to be created.
Please add a host-only network to the machine (with either DHCP or a
static IP) for NFS to work.

**Comment by binocarlos** [comment]
Hi - thanks for the feedback...

So something is odd with the output you pasted - after having done:

``` bash
$ git clone https://github.com/binocarlos/powerstrip-k8s-demo
$ cd powerstrip-k8s-demo
$ vagrant up
```

Here is the output that is expected:

```
$ vagrant up
Bringing machine 'node1' up with 'virtualbox' provider...
Bringing machine 'node2' up with 'virtualbox' provider...
Bringing machine 'master' up with 'virtualbox' provider...
==> node1: Importing base box 'powerstrip-k8s-demo-v1'...
```

As you can see - there are 3 nodes named (node1,node2,master) - also, the base box is `powerstrip-k8s-demo-v1`

In your example - there is 1 node named (default) and the base box is `hashicorp/precise32`

Are you sure you are doing `vagrant up` from inside the `powerstrip-k8s-demo` folder?

If yes - something very odd is going on - what is the output of `vagrant --version`?

**Comment by peterlamar** [comment]
Indeed, I was on version 1.6.3. I upgraded to version 1.7.2 and it seems to be working now. So perhaps ask for the latest vagrant and call it a day? Either way I appear to be unblocked and I really appreciate your help!
